# Generated by Django 4.2.3 on 2023-07-21 09:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('model', models.CharField(max_length=100, verbose_name='модель')),
                ('number', models.CharField(max_length=9, verbose_name='номер')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='дата окончания')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('fuel_consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='расход топлива')),
                ('year_of_manufacture', models.PositiveIntegerField(blank=True, null=True, verbose_name='год выпуска')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN')),
                ('chassis_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='номер шасси')),
                ('body_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='номер кузова')),
                ('engine_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='номер двигателя')),
                ('engine_volume', models.CharField(blank=True, max_length=50, null=True, verbose_name='объем')),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='тип топлива')),
                ('fuel_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='номер топливной карты')),
                ('inspection_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер ТО')),
                ('inspection_expiry_date', models.DateField(blank=True, null=True, verbose_name='срок действия ТО')),
            ],
            options={
                'verbose_name': 'Технику',
                'verbose_name_plural': 'Техника',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'Тип техники',
                'verbose_name_plural': 'Тип техники',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=15, verbose_name='телефон')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Leasing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100, verbose_name='банк')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма')),
                ('term', models.IntegerField(verbose_name='срок')),
                ('monthly_payment_date', models.PositiveIntegerField(verbose_name='дата ежемесячного погашения')),
            ],
            options={
                'verbose_name': 'Лизинг',
                'verbose_name_plural': 'Лизинг',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(max_length=20, verbose_name='тип владельца')),
                ('name', models.CharField(max_length=20, verbose_name='наименование')),
                ('INN', models.IntegerField(verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Владельца',
                'verbose_name_plural': 'Владельцы',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='дата начала')),
                ('end_date', models.DateField(verbose_name='дата окончания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.car', verbose_name='техника')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'Аренду',
                'verbose_name_plural': 'Аренды',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название тарифа')),
                ('min_days', models.PositiveIntegerField(verbose_name='минимальное количество дней')),
                ('max_days', models.PositiveIntegerField(verbose_name='максимальное количество дней')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='полное имя')),
                ('mobile_numer', models.CharField(max_length=50, verbose_name='мобильный номер')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='почасовая ставка')),
                ('passport', models.CharField(max_length=50, verbose_name='паспорт')),
            ],
            options={
                'verbose_name': 'Оператора',
                'verbose_name_plural': 'Операторы',
            },
        ),
        migrations.CreateModel(
            name='IndividualClient',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.client')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
            },
            bases=('tracker.client',),
        ),
        migrations.CreateModel(
            name='LegalClient',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.client')),
                ('company_name', models.CharField(max_length=100, verbose_name='название компании')),
                ('vat_number', models.CharField(max_length=20, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
            },
            bases=('tracker.client',),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_filled', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='заправленное топливо')),
                ('fuel_consumed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='расход топлива')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(verbose_name='время начала')),
                ('end_time', models.TimeField(verbose_name='время окончания')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='tracker.rental', verbose_name='аренда')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.worker', verbose_name='рабочий')),
            ],
            options={
                'verbose_name': 'Смену',
                'verbose_name_plural': 'Смены',
            },
        ),
        migrations.AddField(
            model_name='rental',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.tariff', verbose_name='тариф'),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osago_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='номер ОСАГО')),
                ('osago_expiry_date', models.DateField(blank=True, null=True, verbose_name='действует до (ОСАГО)')),
                ('kasko_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='номер КАСКО')),
                ('kasko_expiry_date', models.DateField(blank=True, null=True, verbose_name='действует до (КАСКО)')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.car', verbose_name='техника')),
            ],
            options={
                'verbose_name': 'Страховка',
                'verbose_name_plural': 'Страховки',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.cartype', verbose_name='тип техники'),
        ),
        migrations.AddField(
            model_name='car',
            name='leasing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.leasing', verbose_name='лизинг'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.owner', verbose_name='владелец'),
        ),
        migrations.CreateModel(
            name='BuildObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название объекта')),
                ('address', models.CharField(max_length=200, verbose_name='адрес объекта')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
