# Generated by Django 4.2.3 on 2023-07-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='build_object',
        ),
        migrations.AddField(
            model_name='buildobject',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.client', verbose_name='клиент'),
            preserve_default=False,
        ),
    ]
