# Generated by Django 4.2.3 on 2023-07-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildobject',
            name='client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.AddField(
            model_name='client',
            name='build_object',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='tracker.buildobject', verbose_name='объект'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualclient',
            name='email',
            field=models.EmailField(default=0, max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualclient',
            name='phone',
            field=models.CharField(default=0, max_length=15, verbose_name='телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalclient',
            name='email',
            field=models.EmailField(default=0, max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalclient',
            name='phone',
            field=models.CharField(default=0, max_length=15, verbose_name='телефон'),
            preserve_default=False,
        ),
    ]
