# Generated by Django 4.2.3 on 2023-07-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_client_build_object_buildobject_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='build_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.buildobject', verbose_name='объект'),
        ),
    ]
