# Generated by Django 4.2.3 on 2023-07-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_buildobject_client_remove_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualclient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='individualclient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='individualclient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='individualclient',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='legalclient',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='legalclient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='legalclient',
            name='phone',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=0, max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default=0, max_length=50, verbose_name='имя/название огранизации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default=0, max_length=15, verbose_name='телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualclient',
            name='passport',
            field=models.CharField(default=0, max_length=12, verbose_name='паспорт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalclient',
            name='reprasintative_name',
            field=models.CharField(default=0, max_length=100, verbose_name='имя представителя'),
            preserve_default=False,
        ),
    ]
