# Generated by Django 4.2.3 on 2023-08-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rental_build_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='rental_files/', verbose_name='договор'),
        ),
        migrations.AddField(
            model_name='rental',
            name='esm7_file',
            field=models.FileField(blank=True, null=True, upload_to='rental_files/', verbose_name='эсм-7'),
        ),
        migrations.AddField(
            model_name='rental',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='rental_files/', verbose_name='счет'),
        ),
        migrations.AddField(
            model_name='rental',
            name='upd_file',
            field=models.FileField(blank=True, null=True, upload_to='rental_files/', verbose_name='упд'),
        ),
        migrations.AddField(
            model_name='rental',
            name='waybill_file',
            field=models.FileField(blank=True, null=True, upload_to='rental_files/', verbose_name='путевой лист'),
        ),
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=10, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='leasing',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='INN',
            field=models.CharField(max_length=15, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=40, verbose_name='наименование'),
        ),
    ]
