# Generated by Django 4.2.3 on 2023-07-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tracker', '0003_remove_individualclient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='content_type',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='client',
            name='object_id',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
